-- MySQL Script generated by MySQL Workbench
-- Thu Apr 28 11:30:00 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema esports
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema esports
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `esports` DEFAULT CHARACTER SET utf8mb4 ;
USE `esports` ;

-- -----------------------------------------------------
-- Table `esports`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esports`.`country` (
  `idcountry` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idcountry`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esports`.`organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esports`.`organization` (
  `idorganization` INT NOT NULL,
  `country_idcountry` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idorganization`),
  INDEX `fk_organization_country1_idx` (`country_idcountry` ASC),
  CONSTRAINT `fk_organization_country1`
    FOREIGN KEY (`country_idcountry`)
    REFERENCES `esports`.`country` (`idcountry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esports`.`team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esports`.`team` (
  `idteam` INT NOT NULL,
  `organization_idorganization` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idteam`),
  INDEX `fk_team_organization_idx` (`organization_idorganization` ASC),
  CONSTRAINT `fk_team_organization`
    FOREIGN KEY (`organization_idorganization`)
    REFERENCES `esports`.`organization` (`idorganization`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esports`.`game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esports`.`game` (
  `idgame` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idgame`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esports`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esports`.`region` (
  `idregion` INT NOT NULL,
  `game_idgame` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idregion`),
  INDEX `fk_region_game1_idx` (`game_idgame` ASC),
  CONSTRAINT `fk_region_game1`
    FOREIGN KEY (`game_idgame`)
    REFERENCES `esports`.`game` (`idgame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esports`.`league`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esports`.`league` (
  `idleague` INT NOT NULL,
  `game_idgame` INT NOT NULL,
  `region_idregion` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `start` DATE NULL,
  `end` DATE NULL,
  PRIMARY KEY (`idleague`),
  INDEX `fk_league_game1_idx` (`game_idgame` ASC),
  INDEX `fk_league_region1_idx` (`region_idregion` ASC),
  CONSTRAINT `fk_league_game1`
    FOREIGN KEY (`game_idgame`)
    REFERENCES `esports`.`game` (`idgame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_league_region1`
    FOREIGN KEY (`region_idregion`)
    REFERENCES `esports`.`region` (`idregion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esports`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esports`.`role` (
  `idrole` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idrole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esports`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esports`.`person` (
  `idperson` INT NOT NULL,
  `country_idcountry` INT NOT NULL,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `nickname` VARCHAR(45) NULL,
  `birthdate` DATE NULL,
  `active` TINYINT NULL,
  PRIMARY KEY (`idperson`),
  INDEX `fk_person_country1_idx` (`country_idcountry` ASC),
  CONSTRAINT `fk_person_country1`
    FOREIGN KEY (`country_idcountry`)
    REFERENCES `esports`.`country` (`idcountry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esports`.`match`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esports`.`match` (
  `idmatch` INT NOT NULL,
  `date` DATE NULL,
  PRIMARY KEY (`idmatch`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esports`.`tournament`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esports`.`tournament` (
  `idtournament` INT NOT NULL,
  `game_idgame` INT NOT NULL,
  `country_idcountry` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `date` DATE NULL,
  PRIMARY KEY (`idtournament`),
  INDEX `fk_tournament_game1_idx` (`game_idgame` ASC),
  INDEX `fk_tournament_country1_idx` (`country_idcountry` ASC),
  CONSTRAINT `fk_tournament_game1`
    FOREIGN KEY (`game_idgame`)
    REFERENCES `esports`.`game` (`idgame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tournament_country1`
    FOREIGN KEY (`country_idcountry`)
    REFERENCES `esports`.`country` (`idcountry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esports`.`tournament_has_team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esports`.`tournament_has_team` (
  `tournament_idtournament` INT NOT NULL,
  `team_idteam` INT NOT NULL,
  PRIMARY KEY (`tournament_idtournament`, `team_idteam`),
  INDEX `fk_tournament_has_team_team1_idx` (`team_idteam` ASC),
  INDEX `fk_tournament_has_team_tournament1_idx` (`tournament_idtournament` ASC),
  CONSTRAINT `fk_tournament_has_team_tournament1`
    FOREIGN KEY (`tournament_idtournament`)
    REFERENCES `esports`.`tournament` (`idtournament`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tournament_has_team_team1`
    FOREIGN KEY (`team_idteam`)
    REFERENCES `esports`.`team` (`idteam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esports`.`league_has_match`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esports`.`league_has_match` (
  `league_idleague` INT NOT NULL,
  `match_idmatch` INT NOT NULL,
  PRIMARY KEY (`league_idleague`, `match_idmatch`),
  INDEX `fk_league_has_match_match1_idx` (`match_idmatch` ASC),
  INDEX `fk_league_has_match_league1_idx` (`league_idleague` ASC),
  CONSTRAINT `fk_league_has_match_league1`
    FOREIGN KEY (`league_idleague`)
    REFERENCES `esports`.`league` (`idleague`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_league_has_match_match1`
    FOREIGN KEY (`match_idmatch`)
    REFERENCES `esports`.`match` (`idmatch`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esports`.`tournament_has_match`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esports`.`tournament_has_match` (
  `tournament_idtournament` INT NOT NULL,
  `match_idmatch` INT NOT NULL,
  PRIMARY KEY (`tournament_idtournament`, `match_idmatch`),
  INDEX `fk_tournament_has_match_match1_idx` (`match_idmatch` ASC),
  INDEX `fk_tournament_has_match_tournament1_idx` (`tournament_idtournament` ASC),
  CONSTRAINT `fk_tournament_has_match_tournament1`
    FOREIGN KEY (`tournament_idtournament`)
    REFERENCES `esports`.`tournament` (`idtournament`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tournament_has_match_match1`
    FOREIGN KEY (`match_idmatch`)
    REFERENCES `esports`.`match` (`idmatch`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esports`.`league_has_team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esports`.`league_has_team` (
  `league_idleague` INT NOT NULL,
  `team_idteam` INT NOT NULL,
  `start` DATE NULL,
  `end` DATE NULL,
  PRIMARY KEY (`league_idleague`, `team_idteam`),
  INDEX `fk_league_has_team_team1_idx` (`team_idteam` ASC),
  INDEX `fk_league_has_team_league1_idx` (`league_idleague` ASC),
  CONSTRAINT `fk_league_has_team_league1`
    FOREIGN KEY (`league_idleague`)
    REFERENCES `esports`.`league` (`idleague`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_league_has_team_team1`
    FOREIGN KEY (`team_idteam`)
    REFERENCES `esports`.`team` (`idteam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esports`.`team_has_person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esports`.`team_has_person` (
  `team_idteam` INT NOT NULL,
  `person_idperson` INT NOT NULL,
  `start` DATE NULL,
  `end` DATE NULL,
  `role_idrole` INT NOT NULL,
  PRIMARY KEY (`team_idteam`, `person_idperson`),
  INDEX `fk_team_has_person_person1_idx` (`person_idperson` ASC),
  INDEX `fk_team_has_person_team1_idx` (`team_idteam` ASC),
  INDEX `fk_team_has_person_role1_idx` (`role_idrole` ASC),
  CONSTRAINT `fk_team_has_person_team1`
    FOREIGN KEY (`team_idteam`)
    REFERENCES `esports`.`team` (`idteam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_team_has_person_person1`
    FOREIGN KEY (`person_idperson`)
    REFERENCES `esports`.`person` (`idperson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_team_has_person_role1`
    FOREIGN KEY (`role_idrole`)
    REFERENCES `esports`.`role` (`idrole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esports`.`person_has_organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esports`.`person_has_organization` (
  `person_idperson` INT NOT NULL,
  `organization_idorganization` INT NOT NULL,
  `start` DATE NULL,
  `end` DATE NULL,
  `role_idrole` INT NOT NULL,
  PRIMARY KEY (`person_idperson`, `organization_idorganization`),
  INDEX `fk_person_has_organization_organization1_idx` (`organization_idorganization` ASC),
  INDEX `fk_person_has_organization_person1_idx` (`person_idperson` ASC),
  INDEX `fk_person_has_organization_role1_idx` (`role_idrole` ASC),
  CONSTRAINT `fk_person_has_organization_person1`
    FOREIGN KEY (`person_idperson`)
    REFERENCES `esports`.`person` (`idperson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_has_organization_organization1`
    FOREIGN KEY (`organization_idorganization`)
    REFERENCES `esports`.`organization` (`idorganization`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_has_organization_role1`
    FOREIGN KEY (`role_idrole`)
    REFERENCES `esports`.`role` (`idrole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esports`.`match_game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esports`.`match_game` (
  `idmatch_game` INT NOT NULL,
  `match_idmatch` INT NOT NULL,
  `winner` INT NOT NULL,
  PRIMARY KEY (`idmatch_game`),
  INDEX `fk_match_game_match1_idx` (`match_idmatch` ASC),
  INDEX `fk_match_game_team1_idx` (`winner` ASC),
  CONSTRAINT `fk_match_game_match1`
    FOREIGN KEY (`match_idmatch`)
    REFERENCES `esports`.`match` (`idmatch`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_match_game_team1`
    FOREIGN KEY (`winner`)
    REFERENCES `esports`.`team` (`idteam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esports`.`match_game_has_team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esports`.`match_game_has_team` (
  `match_game_idmatch_game` INT NOT NULL,
  `team_idteam` INT NOT NULL,
  PRIMARY KEY (`match_game_idmatch_game`, `team_idteam`),
  INDEX `fk_match_game_has_team_team1_idx` (`team_idteam` ASC),
  INDEX `fk_match_game_has_team_match_game1_idx` (`match_game_idmatch_game` ASC),
  CONSTRAINT `fk_match_game_has_team_match_game1`
    FOREIGN KEY (`match_game_idmatch_game`)
    REFERENCES `esports`.`match_game` (`idmatch_game`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_match_game_has_team_team1`
    FOREIGN KEY (`team_idteam`)
    REFERENCES `esports`.`team` (`idteam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esports`.`match_game_has_person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esports`.`match_game_has_person` (
  `match_game_idmatch_game` INT NOT NULL,
  `person_idperson` INT NOT NULL,
  PRIMARY KEY (`match_game_idmatch_game`, `person_idperson`),
  INDEX `fk_match_game_has_person_person1_idx` (`person_idperson` ASC),
  INDEX `fk_match_game_has_person_match_game1_idx` (`match_game_idmatch_game` ASC),
  CONSTRAINT `fk_match_game_has_person_match_game1`
    FOREIGN KEY (`match_game_idmatch_game`)
    REFERENCES `esports`.`match_game` (`idmatch_game`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_match_game_has_person_person1`
    FOREIGN KEY (`person_idperson`)
    REFERENCES `esports`.`person` (`idperson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
